name: GoFundMe Scraper

on:
  schedule:
    # Run every hour on the hour
    - cron: "0 * * * *"
  workflow_dispatch:  # Allow manual run from GitHub UI

permissions:
  contents: write   # ✅ allow git push using GITHUB_TOKEN
  
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run GoFundMe scraper
        run: |
          echo "Running GoFundMe scraper..."
          python scripts/gofundme_scraper.py > amount.txt
          echo "Scraped amount:"
          cat amount.txt

      - name: Commit updated amount.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add amount.txt
          # Only commit if file content actually changed
          git diff --cached --quiet || git commit -m "Update amount.txt [skip ci]"
          git push
